export const links = {
  home: 'https://datahub.vana.com/',
  explorer: 'https://vanascan.io/',
  discord: 'https://discord.com/app/invite-with-guild-onboarding/withvana',
  github: 'https://github.com/vana-com',
  docs: 'https://docs.vana.org/',
  warpDocs: 'https://docs.hyperlane.xyz/docs/reference/applications/warp-routes',
  gasDocs: 'https://docs.hyperlane.xyz/docs/reference/hooks/interchain-gas',
  chains: 'https://docs.hyperlane.xyz/docs/resources/domains',
  twitter: 'https://x.com/withvana',
  blog: 'https://medium.com/hyperlane',
  tos: 'https://www.vana.org/legal/terms-conditions',
  privacyPolicy: 'https://www.vana.org/legal/privacy-policy',
  bounty: 'https://vana.org',
};
