# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - addressOrDenom: "0x3e6Dba802d62aba2361Dd632fbC9f547AA6789aE"
    chainName: ethereum
    connections:
      - token: ethereum|vana|0x3e6Dba802d62aba2361Dd632fbC9f547AA6789aE
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
    logoURI: /logos/eth.svg
  - addressOrDenom: "0x3e6Dba802d62aba2361Dd632fbC9f547AA6789aE"
    chainName: vana
    connections:
      - token: ethereum|ethereum|0x3e6Dba802d62aba2361Dd632fbC9f547AA6789aE
    decimals: 18
    name: Ether
    standard: EvmHypSynthetic
    symbol: WETH
    logoURI: /logos/eth.svg
  - addressOrDenom: "0x177778F19E89dD1012BdBe603F144088A95C4B53"
    chainName: ethereum
    connections:
      - token: ethereum|vana|0x96b572D2d880cf2Fa2563651BD23ADE6f5516652
    decimals: 18
    name: Vana
    standard: EvmHypSynthetic
    symbol: WVANA
    logoURI: /logos/vana.svg
  - addressOrDenom: "0x96b572D2d880cf2Fa2563651BD23ADE6f5516652"
    chainName: vana
    connections:
      - token: ethereum|ethereum|0x177778F19E89dD1012BdBe603F144088A95C4B53
    decimals: 18
    name: Vana
    standard: EvmHypNative
    symbol: VANA
    logoURI: /logos/vana.svg
options: {}
