# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x56cb359B57d67B80Ce36C20245aDBF6ff3Ae0067"
    chainName: atn
    connections:
      - token: ethereum|sepolia|0x4C4F2C8ddA54F0790F1B6eE005085Cb788AC7eDE
    decimals: 18
    name: tAI3
    standard: EvmHypNative
    symbol: tAI3
    logoURI: /logos/tatc.svg
  - addressOrDenom: "0x4C4F2C8ddA54F0790F1B6eE005085Cb788AC7eDE"
    chainName: sepolia
    connections:
      - token: ethereum|atn|0x56cb359B57d67B80Ce36C20245aDBF6ff3Ae0067
    decimals: 18
    name: tAI3
    standard: EvmHypSynthetic
    symbol: WAI3
    logoURI: /logos/tatc.svg
  - addressOrDenom: "0x95C0E11356D90D498A7493D594Be7de4d85F8b49"
    chainName: atn
    standard: EvmHypSynthetic
    decimals: 18
    symbol: WETH
    name: Wrapped Ether
    connections:
      - token: ethereum|sepolia|0xF515BC8231208b1caB2294ad077c0942bd6a7972
    logoURI: /logos/eth.svg
  - addressOrDenom: "0xF515BC8231208b1caB2294ad077c0942bd6a7972"
    chainName: sepolia
    standard: EvmHypNative
    decimals: 18
    symbol: ETH
    name: Wrapped Ether
    connections:
      - token: ethereum|atn|0x95C0E11356D90D498A7493D594Be7de4d85F8b49
    logoURI: /logos/eth.svg
  - chainName: atn
    standard: EvmHypCollateral
    decimals: 18
    symbol: twsol
    name: TestWrappedSolanaToken
    addressOrDenom: "0x3F0b455E1D785BE2CDE774eEee7806ABd7098c30"
    collateralAddressOrDenom: "0x22a79c7F77696f7Ecf161B2Ad4890eD759895aB4"
    connections:
      - token: sealevel|solanatestnet|9XZTUugZg9XpZMBPZbRr2hFTsykoKTfEJbYM2iAmvrx5
    logoURI: /logos/solana.svg
  - chainName: solanatestnet
    standard: SealevelHypSynthetic
    decimals: 9
    symbol: twsol
    name: TestWrappedSolanaToken
    addressOrDenom: "9XZTUugZg9XpZMBPZbRr2hFTsykoKTfEJbYM2iAmvrx5"
    connections:
      - token: ethereum|atn|0x3F0b455E1D785BE2CDE774eEee7806ABd7098c30
    logoURI: /logos/solana.svg
  
options: {}