# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
# yaml-language-server: $schema=../schema.json
tokens:
  - chainName: amn
    standard: EvmHypNative
    decimals: 18
    symbol: AI3
    name: AI3
    logoURI: /logos/tatc.svg
    addressOrDenom: "0x38ED676d20C9b026A2372D3A88a0bcEE54de3851"
    connections:
      - token: ethereum|ethereum|0x363FCa95F23E10C76ef793D62d92d39e89d83AC1
  - chainName: ethereum
    standard: EvmHypSynthetic
    decimals: 18
    symbol: WAI3
    name: WAI3
    logoURI: /logos/tatc.svg
    addressOrDenom: "0x363FCa95F23E10C76ef793D62d92d39e89d83AC1"
    connections:
      - token: ethereum|amn|0x38ED676d20C9b026A2372D3A88a0bcEE54de3851
  - chainName: amn
    standard: EvmHypSynthetic
    decimals: 18
    symbol: WETH
    name: Wrapped ETH
    logoURI: /logos/eth.svg
    addressOrDenom: "0x0539001D7BF886b147Ed92A5fd552cc9D4e80CE8"
    connections:
      - token: ethereum|ethereum|0x67051Bb2602793E1B183bC414aCdccEBAa224433
  - chainName: ethereum
    standard: EvmHypNative
    decimals: 18
    symbol: ETH
    name: Ether
    logoURI: /logos/eth.svg
    addressOrDenom: "0x67051Bb2602793E1B183bC414aCdccEBAa224433"
    connections:
      - token: ethereum|amn|0x0539001D7BF886b147Ed92A5fd552cc9D4e80CE8
  - chainName: amn
    standard: EvmHypNative
    decimals: 18
    symbol: AI3
    name: AI3
    logoURI: /logos/tatc.svg
    addressOrDenom: "0x0cEbaeF23bA9dE31444C0623bd47F3df7fb88ed2"
    connections:
      - token: ethereum|bsc|0x220375118d0600a8FCe7Bf1AaD5fcf2AE6ED069B
  - chainName: bsc
    standard: EvmHypSynthetic
    decimals: 18
    symbol: WAI3
    name: WAI3
    logoURI: /logos/tatc.svg
    addressOrDenom: "0x220375118d0600a8FCe7Bf1AaD5fcf2AE6ED069B"
    connections:
      - token: ethereum|amn|0x0cEbaeF23bA9dE31444C0623bd47F3df7fb88ed2
  - chainName: amn
    standard: EvmHypSynthetic
    decimals: 18
    symbol: WBNB
    name: WBNB
    logoURI: /logos/bsc.svg
    addressOrDenom: "0x94D72DFE3d977217eB7C936C6762A6E5457f82Fb"
    connections:
      - token: ethereum|bsc|0x55fe96a67a95cA8753fD4FE040F22F53B75B92cF
  - chainName: bsc
    standard: EvmHypNative
    decimals: 18
    symbol: BNB
    name: BNB
    logoURI: /logos/bsc.svg
    addressOrDenom: "0x55fe96a67a95cA8753fD4FE040F22F53B75B92cF"
    connections:
      - token: ethereum|amn|0x94D72DFE3d977217eB7C936C6762A6E5457f82Fb
  - chainName: amn
    standard: EvmHypCollateralFiat
    decimals: 6
    symbol: USDC.e
    name: Bridged USDC (Autonomys)
    logoURI: /logos/usdc.svg
    addressOrDenom: "0x98d0238e245CeFBD8846821D8CDdB0593ef32ec6"
    collateralAddressOrDenom: "0xD80173DB7651f8f820180AEa0ca6C1c1C0D4F19A"
    connections:
      - token: ethereum|ethereum|0xa4f50a4263706314131336F643699FD6FD97309F
  - chainName: ethereum
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDC
    name: USD Coin
    logoURI: /logos/usdc.svg
    addressOrDenom: "0xa4f50a4263706314131336F643699FD6FD97309F"
    collateralAddressOrDenom: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    connections:
      - token: ethereum|amn|0x98d0238e245CeFBD8846821D8CDdB0593ef32ec6

  - chainName: solanamainnet
    standard: SealevelHypNative
    decimals: 9
    symbol: SOL
    name: Wrapped SOL
    logoURI: /logos/solana.svg
    addressOrDenom: Fspt3tEJVjDcQZ96TeukKBc5AFmoKDKUfVj78KnSrNdb
    connections:
      - token: ethereum|amn|0x0000AF4EAB3Eb8B1Be4E2e925C982393F6bf8bb6
  - chainName: amn
    standard: EvmHypSynthetic
    decimals: 9
    symbol: wSOL
    name: Wrapped SOL
    logoURI: /logos/solana.svg
    addressOrDenom: "0x0000AF4EAB3Eb8B1Be4E2e925C982393F6bf8bb6"
    connections:
      - token: sealevel|solanamainnet|Fspt3tEJVjDcQZ96TeukKBc5AFmoKDKUfVj78KnSrNdb

  - chainName: solanamainnet
    standard: SealevelHypSynthetic
    decimals: 9
    symbol: WAI3
    name: Wrapped AI3
    logoURI: /logos/tatc.svg
    addressOrDenom: 8HhMERjk5pXpA4Zmv9y68z5jaWd7qoZg3qtY8cGC3V4Z
    mailbox: H9fQ4JAahkhbNk1eMQd43WYhXYBXT7LMsZ9eXPMo6NrM
    collateralAddressOrDenom: veS2vDmcRY1Bd1zsC1TLiG85rXSwz119UCZAvNZBt7n
    connections:
      - token: ethereum|amn|0x095023fb8F85c96C766E8e00927E6DB6316EE9Eb
  - chainName: amn
    standard: EvmHypNative
    decimals: 18
    symbol: AI3
    name: AI3
    logoURI: /logos/tatc.svg
    addressOrDenom: "0x095023fb8F85c96C766E8e00927E6DB6316EE9Eb"
    connections:
      - token: sealevel|solanamainnet|8HhMERjk5pXpA4Zmv9y68z5jaWd7qoZg3qtY8cGC3V4Z

options: {}
