# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
# yaml-language-server: $schema=../schema.json
tokens:
  - chainName: acn
    standard: EvmHypNative
    decimals: 18
    symbol: tAI3
    name: tAI3
    logoURI: /logos/tatc.svg
    addressOrDenom: "0xb15B0C489215a26c455F593fDb5bf545559e3884"
    connections:
      - token: ethereum|sepolia|0x258C5C9926f0cC73B97d987A459b461D712BFe77
  - chainName: sepolia
    standard: EvmHypSynthetic
    decimals: 18
    symbol: wtAI3
    name: wtAI3
    logoURI: /logos/tatc.svg
    addressOrDenom: "0x258C5C9926f0cC73B97d987A459b461D712BFe77"
    connections:
      - token: ethereum|acn|0xb15B0C489215a26c455F593fDb5bf545559e3884
  - chainName: acn
    standard: EvmHypNative
    decimals: 18
    symbol: tAI3
    name: tAI3
    logoURI: /logos/tatc.svg
    addressOrDenom: "0x258C5C9926f0cC73B97d987A459b461D712BFe77"
    connections:
      - token: ethereum|bsctestnet|0xe4Cc17396D13f40e0B2bfE41bfe84cb7D427361C
  - chainName: bsctestnet
    standard: EvmHypSynthetic
    decimals: 18
    symbol: twAI3
    name: twAI3
    logoURI: /logos/tatc.svg
    addressOrDenom: "0xe4Cc17396D13f40e0B2bfE41bfe84cb7D427361C"
    connections:
      - token: ethereum|acn|0x258C5C9926f0cC73B97d987A459b461D712BFe77
  - chainName: acn
    standard: EvmHypSynthetic
    decimals: 18
    symbol: WBNB
    name: WBNB
    logoURI: /logos/bsc.svg
    addressOrDenom: "0xb1Aa2690470A9302689b2B3c070C8937c063f28D"
    connections:
      - token: ethereum|bsctestnet|0x6BE33cb2D56bFa8471Db953986898e1C0872BF38
  - chainName: bsctestnet
    standard: EvmHypNative
    decimals: 18
    symbol: BNB
    name: BNB
    logoURI: /logos/bsc.svg
    addressOrDenom: "0x6BE33cb2D56bFa8471Db953986898e1C0872BF38"
    connections:
      - token: ethereum|acn|0xb1Aa2690470A9302689b2B3c070C8937c063f28D
  - chainName: acn
    standard: EvmHypSynthetic
    decimals: 18
    symbol: WETH
    name: WETH
    logoURI: /logos/eth.svg
    addressOrDenom: "0x2601056eCc40b13F68B68D96c827DffcDf1cB902"
    connections:
      - token: ethereum|sepolia|0xb1Aa2690470A9302689b2B3c070C8937c063f28D
  - chainName: sepolia
    standard: EvmHypNative
    decimals: 18
    symbol: ETH
    name: Ether
    logoURI: /logos/eth.svg
    addressOrDenom: "0xb1Aa2690470A9302689b2B3c070C8937c063f28D"
    connections:
      - token: ethereum|acn|0x2601056eCc40b13F68B68D96c827DffcDf1cB902


options: {}